<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- Unique metadata for this project -->
    <Description>ASP.NET Core Web API layer for GaDeMa</Description>
    <Product>Gadema.Api</Product>
  </PropertyGroup>

  <ItemGroup>
    <!-- Project References -->
    <ProjectReference Include="../Gadema.Data/Gadema.Data.csproj" />
    <ProjectReference Include="../Gadema.Core/Gadema.Core.csproj" />
    
    <!-- API-specific dependencies (Versions managed by Directory.Build.props) -->
    <PackageReference Include="Microsoft.AspNetCore.Http" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore">
      <Version>2.17.7</Version>
    </PackageReference>
    
    <PackageReference Include="Google.Apis.Auth" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="QuestPDF" />
  </ItemGroup>

</Project>