// =============================================================================

// Gadema.Core - Shared Domain Models & Interfaces

// =============================================================================

using Gadema.Core.Models.Base.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Gadema.Data.Configurations.Versioning;

/// <summary>
/// Configuration for ContentSnapshot entity in game development management system.
/// </summary>
public class ContentSnapshotEntityTypeConfiguration : IEntityTypeConfiguration<ContentSnapshot>
{
    /// <summary>
    /// Configure ContentSnapshot entity properties and relationships.
    /// Backs the "Save Ritual" (Phase 5) - stores intentional milestones with user-provided context.
    /// Supports the horizontal timeline in the Top Panel and History tab in the Right Panel.
    /// </summary>
    public void Configure(EntityTypeBuilder<ContentSnapshot> builder)
    {
        // Primary key
        builder.HasKey(e => e.Id);
        
        // Indexes for frequently filtered columns
        builder.HasIndex(e => e.MetaInfoId);
        builder.HasIndex(e => e.VersionNumber);  // Sequential versioning for timeline
        builder.HasIndex(e => e.SnapshotType);
        builder.HasIndex(e => e.CreatedByUserId);
        builder.HasIndex(e => e.CreatedAt);  // Query recent snapshots
        
        // Navigation property: ContentMetaInfo (ContentMetaInfo)
        builder.HasOne(cs => cs.ContentMetaInfo)
            .WithMany()
            .HasForeignKey(cs => cs.MetaInfoId)
            .OnDelete(DeleteBehavior.Cascade);  // Cascade delete snapshot when content item deleted
        
        // Properties configuration
        builder.Property(e => e.Comment).HasMaxLength(512);  // User-provided reason for saving
        builder.Property(e => e.VersionNumber).HasDefaultValue(0);  // Sequential versioning
        builder.Property(e => e.SnapshotType).HasDefaultValue(0);  // AutoGenerated
        builder.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP");
    }
}
