/// <summary>
/// Data transfer object for creating a new content snapshot (part of the Save Ritual).
/// </summary>
public class ContentSnapshotUpdateDto
{
    /// <summary>
    /// The unique identifier of the meta-information record this snapshot belongs to.
    /// </summary>
    [Required]
    public Guid MetaInfoId { get; set; }

    /// <summary>
    /// An optional user-provided comment explaining why this snapshot was captured.
    /// </summary>
    [MaxLength(512)]
    public string? Comment { get; set; }

    /// <summary>
    /// The type of snapshot: 0=AutoGenerated, 1=ManualSave, 2=RollbackPoint.
    /// </summary>
    public int SnapshotType { get; set; } = 1;

    /// <summary>
    /// The serialized JSON data representing the state of the content at this moment.
    /// </summary>
    [MaxLength(8192)]
    public string? SnapshotDataJson { get; set; }
}

/// <summary>
/// Represents a captured state (snapshot) of a content item for versioning and recovery.
/// </summary>
public class ContentSnapshotResponseDto
{
    /// <summary>
    /// The unique identifier of the snapshot record.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// The ID of the meta-information record this snapshot belongs to.
    /// </summary>
    public Guid MetaInfoId { get; set; }

    /// <summary>
    /// An optional comment associated with this snapshot.
    /// </summary>
    public string? Comment { get; set; }

    /// <summary>
    /// The version number at which this snapshot was taken.
    /// </summary>
    public int VersionNumber { get; set; }

    /// <summary>
    /// The type of snapshot (e.g., AutoGenerated, Manual).
    /// </summary>
    public int SnapshotType { get; set; }

    /// <summary>
    /// The ID of the user who triggered this snapshot.
    /// </summary>
    public Guid CreatedByUserId { get; set; }

    /// <summary>
    /// The timestamp when the snapshot was created in UTC.
    /// </summary>
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// A paginated list response for content snapshots.
/// </summary>
public class ContentSnapshotListResponseDto
{
    /// <summary>
    /// The collection of retrieved snapshots.
    /// </summary>
    public IEnumerable<ContentSnapshotResponseDto> Items { get; set; } = Enumerable.Empty<ContentSnapshotResponseDto>();

    /// <summary>
    /// Total number of records available across all pages.
    /// </summary>
    public int TotalCount { get; set; }

    /// <summary>
    /// The current page index (1-based).
    /// </summary>
    public int PageNumber { get; set; }

    /// <summary>
    /// The number of items per page.
    /// </summary>
    public int PageSize { get; set; }
}
