// =============================================================================
using System.ComponentModel.DataAnnotations;

namespace Gadema.Core.Dtos.Base.Infrastructure;

/// <summary>
/// DTO for creating a content snapshot (save ritual).
/// </summary>
public class ContentSnapshotUpdateDto
{
    /// <summary>
    /// ID of the content item this snapshot belongs to.
    /// </summary>
    [Required]
    public Guid MetaInfoId { get; set; }

    /// <summary>
    /// User-provided comment explaining why this snapshot was saved.
    /// </summary>
    [MaxLength(512)]
    public string? Comment { get; set; }

    /// <summary>
    /// Snapshot type: 0=AutoGenerated, 1=ManualSave, 2=RollbackPoint.
    /// </summary>
    public int SnapshotType { get; set; } = 1;

    /// <summary>
    /// JSON data for the snapshot.
    /// </summary>
    [MaxLength(8192)]
    public string? SnapshotDataJson { get; set; }
}

/// <summary>
/// Response DTO for a content snapshot.
/// </summary>
public class ContentSnapshotResponseDto
{
    public Guid Id { get; set; }
    public Guid MetaInfoId { get; set; }
    public string? Comment { get; set; }
    public int VersionNumber { get; set; }
    public int SnapshotType { get; set; }
    public Guid CreatedByUserId { get; set; }
    public DateTime CreatedAt { get; set; }
}

/// <summary>
/// List response for content snapshots.
/// </summary>
public class ContentSnapshotListResponseDto
{
    public IEnumerable<ContentSnapshotResponseDto> Items { get; set; } = Enumerable.Empty<ContentSnapshotResponseDto>();
    public int TotalCount { get; set; }
    public int PageNumber { get; set; }
    public int PageSize { get; set; }
}
