namespace Gadema.Core.Models.Base.Infrastructure;

/// <summary>
/// Represents a content snapshot for the "Save Ritual", allowing users to create intentional milestones.
/// These snapshots provide version control and are used to populate the timeline view in the UI.
/// </summary>
[ModelDependency(typeof(ContentMetaInfo))]
public class ContentSnapshot
{
    /// <summary>
    /// Gets or sets the unique identifier for this content snapshot.
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();
    
    /// <summary>
    /// Gets or sets the identifier of the associated content item.
    /// </summary>
    [Required]
    public Guid MetaInfoId { get; set; }
    
    /// <summary>
    /// Gets or sets the associated content meta information entity.
    /// </summary>
    [ForeignKey("MetaInfoId")]
    public virtual ContentMetaInfo ContentMetaInfo { get; set; } = null!;
    /// <summary>
    /// Gets or sets an optional user-provided comment explaining the reason for this snapshot (e.g., "End of chapter 1").
    /// </summary>
    [MaxLength(512)]
    public string? Comment { get; set; }
    
    /// <summary>
    /// Gets or sets the sequential version number for the content item, used for timeline display.
    /// </summary>
    public int VersionNumber { get; set; }
    /// <summary>
    /// Gets or sets the type of snapshot (e.g., Auto-Generated, Manual Save, or Rollback Point).
    /// </summary>
    public int SnapshotType { get; set; }  // Enum: AutoGenerated, ManualSave, RollbackPoint
    /// <summary>
    /// Gets or sets the identifier of the user who created this snapshot.
    /// </summary>
    [Required]
    public Guid CreatedByUserId { get; set; }
    
    /// <summary>
    /// Gets or sets the timestamp when the snapshot was captured.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// Gets or sets the serialized JSON data representing the state of the content at the time of the snapshot.
    /// </summary>
    public string SnapshotDataJson { get; set; }
}