using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Gadema.Core.Models.Base.MetaInfo;

namespace Gadema.Core.Models.Base.Infrastructure;

/// <summary>
/// Represents a content snapshot for the "Save Ritual" (Phase 5).
/// Stores intentional milestones with user-provided context for version control.
/// Backs the horizontal timeline in the Top Panel and History tab in the Right Panel.
/// </summary>
[ModelDependency(typeof(ContentMetaInfo))]
public class ContentSnapshot
{
    /// <summary>
    /// Unique identifier for the content snapshot.
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();
    
    /// <summary>
    /// ID of the content item this snapshot belongs to.
    /// Links to ContentMetaInfo (ContentMetaInfo) for the saved scene/outline/etc.
    /// </summary>
    [Required]
    public Guid MetaInfoId { get; set; }
    
    // Navigation property: ContentMetaInfo (ContentMetaInfo)
    [ForeignKey("MetaInfoId")]
    public virtual ContentMetaInfo ContentMetaInfo { get; set; } = null!;
    
    /// <summary>
    /// User-provided comment explaining why this snapshot was saved.
    /// Answer to the prompt: "Why did you save here?"
    /// </summary>
    [MaxLength(512)]
    public string? Comment { get; set; }
    
    /// <summary>
    /// Sequential version number for timeline display.
    /// Incremented with each new snapshot for the same content item.
    /// </summary>
    public int VersionNumber { get; set; }
    
    /// <summary>
    /// Snapshot type: 0=AutoGenerated, 1=ManualSave (Snapshot), 2=RollbackPoint.
    /// Distinguishes between silent minor saves and intentional snapshot saves.
    /// </summary>
    public int SnapshotType { get; set; }  // Enum: AutoGenerated, ManualSave, RollbackPoint
    
    /// <summary>
    /// ID of the user who created this snapshot.
    /// </summary>
    [Required]
    public Guid CreatedByUserId { get; set; }
    
    /// <summary>
    /// Timestamp when the snapshot was created.
    /// Used to build the horizontal timeline in the UI.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public string SnapshotDataJson { get; set; }
}