### YamlMime:ManagedReference
items:
- uid: Gadema.Data.Configurations.Writing.Narrative
  commentId: N:Gadema.Data.Configurations.Writing.Narrative
  id: Gadema.Data.Configurations.Writing.Narrative
  children:
  - Gadema.Data.Configurations.Writing.Narrative.DialogueBranchEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.DialogueNodeEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.FactionEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.LoreEntryEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.OutlineSectionEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.SceneEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.SceneSegmentEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.SceneStoryBeatMappingEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.StoryBeatEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.StoryChapterEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.StoryEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.StoryOutlineEntityTypeConfiguration
  - Gadema.Data.Configurations.Writing.Narrative.WorldLocationEntityTypeConfiguration
  langs:
  - csharp
  - vb
  name: Gadema.Data.Configurations.Writing.Narrative
  nameWithType: Gadema.Data.Configurations.Writing.Narrative
  fullName: Gadema.Data.Configurations.Writing.Narrative
  type: Namespace
  assemblies:
  - Gadema.Data
references:
- uid: Gadema.Data.Configurations.Writing.Narrative.DialogueBranchEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.DialogueBranchEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.DialogueBranchEntityTypeConfiguration.html
  name: DialogueBranchEntityTypeConfiguration
  nameWithType: DialogueBranchEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.DialogueBranchEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.DialogueNodeEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.DialogueNodeEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.DialogueNodeEntityTypeConfiguration.html
  name: DialogueNodeEntityTypeConfiguration
  nameWithType: DialogueNodeEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.DialogueNodeEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.FactionEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.FactionEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.FactionEntityTypeConfiguration.html
  name: FactionEntityTypeConfiguration
  nameWithType: FactionEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.FactionEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.LoreEntryEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.LoreEntryEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.LoreEntryEntityTypeConfiguration.html
  name: LoreEntryEntityTypeConfiguration
  nameWithType: LoreEntryEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.LoreEntryEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.OutlineSectionEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.OutlineSectionEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.OutlineSectionEntityTypeConfiguration.html
  name: OutlineSectionEntityTypeConfiguration
  nameWithType: OutlineSectionEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.OutlineSectionEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.SceneEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.SceneEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.SceneEntityTypeConfiguration.html
  name: SceneEntityTypeConfiguration
  nameWithType: SceneEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.SceneEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.SceneSegmentEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.SceneSegmentEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.SceneSegmentEntityTypeConfiguration.html
  name: SceneSegmentEntityTypeConfiguration
  nameWithType: SceneSegmentEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.SceneSegmentEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.SceneStoryBeatMappingEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.SceneStoryBeatMappingEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.SceneStoryBeatMappingEntityTypeConfiguration.html
  name: SceneStoryBeatMappingEntityTypeConfiguration
  nameWithType: SceneStoryBeatMappingEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.SceneStoryBeatMappingEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.StoryBeatEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.StoryBeatEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.StoryBeatEntityTypeConfiguration.html
  name: StoryBeatEntityTypeConfiguration
  nameWithType: StoryBeatEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.StoryBeatEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.StoryChapterEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.StoryChapterEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.StoryChapterEntityTypeConfiguration.html
  name: StoryChapterEntityTypeConfiguration
  nameWithType: StoryChapterEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.StoryChapterEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.StoryEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.StoryEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.StoryEntityTypeConfiguration.html
  name: StoryEntityTypeConfiguration
  nameWithType: StoryEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.StoryEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.StoryOutlineEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.StoryOutlineEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.StoryOutlineEntityTypeConfiguration.html
  name: StoryOutlineEntityTypeConfiguration
  nameWithType: StoryOutlineEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.StoryOutlineEntityTypeConfiguration
- uid: Gadema.Data.Configurations.Writing.Narrative.WorldLocationEntityTypeConfiguration
  commentId: T:Gadema.Data.Configurations.Writing.Narrative.WorldLocationEntityTypeConfiguration
  href: Gadema.Data.Configurations.Writing.Narrative.WorldLocationEntityTypeConfiguration.html
  name: WorldLocationEntityTypeConfiguration
  nameWithType: WorldLocationEntityTypeConfiguration
  fullName: Gadema.Data.Configurations.Writing.Narrative.WorldLocationEntityTypeConfiguration
