<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <!-- Unique metadata for this project -->
    <Description>Blazor Web Application for GaDeMa</Description>
    <Product>Gadema.WebApp</Product>
  </PropertyGroup>

  <ItemGroup>
    <!-- Project Reference -->
    <PackageReference Include="MudBlazor" Version="9.10.0" />
    <ProjectReference Include="../Gadema.Core/Gadema.Core.csproj" />

    <!-- UI-specific dependencies (Versions managed by Directory.Build.props) -->
    
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

</Project>