// =============================================================================
using System.ComponentModel.DataAnnotations;

namespace Gadema.Core.Dtos.Authentication;

/// <summary>
/// DTO for enabling two-factor authentication.
/// </summary>
public class Enable2FADto
{
    /// <summary>
    /// The 6-digit TOTP code generated by the user's authenticator app.
    /// Required before QR code generation to prove possession of the device.
    /// </summary>
    [Required(ErrorMessage = "Verification code is required")]
    [StringLength(6, MinimumLength = 6, ErrorMessage = "Code must be exactly 6 digits long.")]
    [RegularExpression(@"^\d{6}$", ErrorMessage = "Code must be a 6-digit numeric value.")]
    public string TwoFactorToken { get; set; } = "";

    /// <summary>
    /// Optional: Recovery code to pre-generate (for user convenience).
    /// If not provided, recovery codes are generated on-demand at login time.
    /// </summary>
    [MaxLength(256)]
    public string? PreGeneratedRecoveryCodes { get; set; } = null!;
}