namespace Gadema.Core.Models.Base.Enums;

/// <summary>
/// Specifies the type of content snapshot for versioning and recovery purposes.
/// </summary>
public enum SnapshotTypeEnum
{
    /// <summary>
    /// An automatically generated snapshot, typically from an autosave mechanism.
    /// </summary>
    [Display(Name = "Auto-Generated")]
    AutoGenerated = 0,

    /// <summary>
    /// A manually created snapshot representing a significant milestone in the user's workflow.
    /// </summary>
    [Display(Name = "Manual Save")]
    ManualSave = 1,

    /// <summary>
    /// A designated point used for disaster recovery or system rollback.
    /// </summary>
    [Display(Name = "Rollback Point")]
    RollbackPoint = 2,
}
