using System.ComponentModel.DataAnnotations;

namespace Gadema.Core.Enums;

/// <summary>
/// Content snapshot types for version control and rollback points.
/// </summary>
public enum SnapshotTypeEnum
{
    /// <summary>
    /// Automatically generated after every save (autosave).
    /// </summary>
    [Display(Name = "Auto-Generated")]
    AutoGenerated = 0,

    /// <summary>
    /// Manually created by user for important milestones.
    /// </summary>
    [Display(Name = "Manual Save")]
    ManualSave = 1,

    /// <summary>
    /// Marked as rollback point for disaster recovery.
    /// </summary>
    [Display(Name = "Rollback Point")]
    RollbackPoint = 2,
}
