<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Unique metadata for this project -->
    <Description>Unit and Integration tests for GaDeMa</Description>
    <Product>Gadema.Tests</Product>
  </PropertyGroup>

  <ItemGroup>
    <!-- Project References -->
    <PackageReference Include="AutoFixture" Version="4.18.1" />
    <ProjectReference Include="..\Gadema.Core\Gadema.Core.csproj" />
    <ProjectReference Include="..\Gadema.Api\Gadema.Api.csproj" />
    
    <!-- Testing dependencies (Versions managed by Directory.Build.props) -->
    
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
  </ItemGroup>

</Project>