// =============================================================================
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
// Gadema.Core - Shared Domain Models & Interfaces
// =============================================================================

namespace Gadema.Core.Models;

/// <summary>
/// Represents a content snapshot for version control and rollback.
/// </summary>
[DependencyResolver.ModelDependency(typeof(ContentItem))]
public class ContentSnapshot
{
    /// <summary>
    /// Unique identifier for the content snapshot.
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();
    
    /// <summary>
    /// ID of the content item this snapshot belongs to.
    /// </summary>
    [Required]
    public Guid ContentItemId { get; set; }
    
    /// <summary>
    /// Snapshot version number.
    /// </summary>
    public int SnapshotVersion { get; set; }
    
    /// <summary>
    /// Snapshot type: 0=AutoGenerated, 1=ManualSave, 2=RollbackPoint.
    /// </summary>
    public int SnapshotType { get; set; }  // Enum: AutoGenerated, ManualSave, RollbackPoint
    
    /// <summary>
    /// Snapshot data as JSON string.
    /// </summary>
    [MaxLength(50000)]
    public string SnapshotDataJson { get; set; } = "";
    
    /// <summary>
    /// ID of the user who created this snapshot.
    /// </summary>
    [Required]
    public Guid CreatedByUserId { get; set; }
    
    /// <summary>
    /// Timestamp when the snapshot was created.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}